CFLAGS  = -mwindows
CFLAGS += -mthreads
CFLAGS += -D_MT
CFLAGS += -Wall
CFLAGS += -Wextra
CFLAGS += -pedantic
CFLAGS += -Weffc++
CFLAGS += -std=c++17
CFLAGS += -O2
CFLAGS += -m64

all:
	${CXX} *.c -o mandelbrot-set-obfuscated.exe ${CFLAGS}
